### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by baldurmen** [leapcode/leap_se#3]
Oï!

On https://leap.se/en/docs/client#user-guide, the "Install guide" link links to https://leap.se/en/docs/client/client/user-install (broken). The "Running guide" also links to something broken

I haven't issued a patch since I'm not certain where is should link to, but my little eye tells me it should be:

>[Install guide](https://leap.se/en/docs/client/user-install)
>[Running guide](https://leap.se/en/docs/client/user-running)

**Comment by elijh** [comment]
thanks for finding that. fixed.
